# Generated by Django 5.2.1 on 2025-05-18 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='file_schema',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message_role',
            field=models.IntegerField(choices=[(1, 'System'), (2, 'Assistant'), (3, 'User')], default=3),
        ),
    ]
