# Generated by Django 5.2.1 on 2025-05-18 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file_file_processed_file_file_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_sqlpath',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
