# Generated by Django 5.2.1 on 2025-05-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_file_file_sqlpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_schema',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_sqlpath',
            field=models.CharField(default='', max_length=255),
        ),
    ]
