# Generated by Django 5.2.1 on 2025-05-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_file_file_schema_alter_file_file_sqlpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
