# Generated by Django 5.2.1 on 2025-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chat_chat_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_role',
            field=models.IntegerField(choices=[(1, 'System'), (2, 'Assistant'), (3, 'User'), (4, 'Internal')], default=3),
        ),
    ]
