# Generated by Django 5.2.1 on 2025-05-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_message_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.file'),
        ),
    ]
