# Generated by Django 5.2.1 on 2025-05-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message_message_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_image_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
