# Generated by Django 5.2.1 on 2025-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_message_message_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_error',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_processed',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Processing'), (3, 'Completed'), (4, 'Failed')], default=1),
        ),
    ]
