# Generated by Django 5.2.1 on 2025-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_file_file_error_alter_file_file_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_business_category',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
